apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80 # The port that other services in Kubernetes can access
    protocol: TCP
    targetPort: 80 # the port on the selected pod(s) that this service accesses.
    nodePort: 30001 