apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: cognixacr.azurecr.io/demoapp/frontendservice:latest
        imagePullPolicy: Always        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
            - name: PORT
              value: "80"
            - name: DATE_API
              value: dateapplication
        ports:
        - containerPort: 80
